item:
  material: STICK
  name: "&bМагическая Палка"
  lore:
    - "&7Держи в левой руке"
    - "&7для +3 блока дистанции"

bonus-reach: 3.0
check-interval: 10 # Тики (20 = 1 сек). Чем меньше, тем отзывчивее смена предмета.